# Generated by Django 4.2.11 on 2025-07-15 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0002_alter_postraw_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postraw',
            name='post_type',
            field=models.IntegerField(choices=[(1, 'admin'), (2, 'user')], default=2),
        ),
    ]
