# Generated by Django 4.2.11 on 2025-07-22 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0004_passwordresetcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postraw',
            name='title',
            field=models.TextField(max_length=50),
        ),
    ]
