# Generated by Django 4.2.11 on 2025-07-22 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0005_alter_postraw_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postraw',
            name='title',
            field=models.TextField(max_length=60),
        ),
    ]
